---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

client_rb:
  treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: package
    run_list:
      - recipe[test::package]
  - name: source-1.6
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.6.14'
        source_url: 'http://www.haproxy.org/download/1.6/src/haproxy-1.6.14.tar.gz'  # yamllint disable-line
        source_checksum: 'bac949838a3a497221d1a9e937d60cba32156783a216146a524ce40675b6b828'  # yamllint disable-line
  - name: source-1.7
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.7.11'
        source_url: 'http://www.haproxy.org/download/1.7/src/haproxy-1.7.11.tar.gz'  # yamllint disable-line
        source_checksum: 'd564b8e9429d1e8e13cb648bf4694926b472e36da1079df946bb732927b232ea'  # yamllint disable-line
  - name: source-1.8
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.8.17'
        source_url: 'http://www.haproxy.org/download/1.8/src/haproxy-1.8.17.tar.gz'  # yamllint disable-line
        source_checksum: '7b789b177875afdd5ddeff058e7efde73aa895dc2dcf728b464358635ae3948e'  # yamllint disable-line
  - name: source-1.9
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.9.2'
        source_url: 'http://www.haproxy.org/download/1.9/src/haproxy-1.9.2.tar.gz'  # yamllint disable-line
        source_checksum: '8dde83374e602a2892c41405f8b4b9ac2d0c76c7a2d103d3a03c7eff1a23a842'  # yamllint disable-line
  - name: config_1
    run_list:
      - recipe[test::config_1]
    includes: centos-7
  - name: config_2
    run_list:
      - recipe[test::config_2]
    includes: centos-7
  - name: config_3
    run_list:
      - recipe[test::config_3]
    includes: centos-7
  - name: config_4
    run_list:
      - recipe[test::config_4]
    includes: centos-7
  - name: config_backend_search
    run_list:
      - recipe[test::config_backend_search]
    includes: centos-7
  - name: config_1_userlist
    run_list:
      - recipe[test::config_1_userlist]
    includes: centos-7
  - name: config_acl
    run_list:
      - recipe[test::config_acl]
    includes: centos-7
  - name: config_resolver
    run_list:
      - recipe[test::config_resolver]
    includes: centos-7
  - name: config_ssl_redirect
    run_list:
      - recipe[test::config_ssl_redirect]
    includes: centos-7
  - name: config_custom_template
    run_list:
      - recipe[test::config_custom_template]
    includes: centos-7
  - name: config_array
    run_list:
      - recipe[test::config_array]
    includes: centos-7
